/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VentanaMaestra.java
 *
 * Created on 20/12/2011, 22:29:26
 */
package main;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Admin
 */
public class VentanaMaestra extends javax.swing.JFrame {

    /** Creates new form VentanaMaestra */
    public VentanaMaestra() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPanelPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuVentanas = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuTodosLosPedidos = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuSalir = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Descargador de pedidos SMK y MAYORISTAS");
        setPreferredSize(new java.awt.Dimension(1000, 600));

        jdpPanelPrincipal.setBackground(new java.awt.Color(0, 0, 51));
        jdpPanelPrincipal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jMenuVentanas.setText("Ventanas");

        jMenuItem1.setText("Pedidos no descargados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuVentanas.add(jMenuItem1);

        jMenuTodosLosPedidos.setText("Todos los pedidos");
        jMenuTodosLosPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTodosLosPedidosActionPerformed(evt);
            }
        });
        jMenuVentanas.add(jMenuTodosLosPedidos);
        jMenuVentanas.add(jSeparator2);

        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuVentanas.add(jMenuSalir);
        jMenuVentanas.add(jSeparator1);

        jMenuBar1.add(jMenuVentanas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 891, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jdpPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        PedNoDesc v = new PedNoDesc();
        jdpPanelPrincipal.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuTodosLosPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTodosLosPedidosActionPerformed
        // TODO add your handling code here:
        PedDesc v = new PedDesc();
        jdpPanelPrincipal.add(v);
        v.setVisible(true);
    }//GEN-LAST:event_jMenuTodosLosPedidosActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                //new VentanaMaestra().setVisible(true);
                try {
                    //new DescargaPedidosADA().setVisible(true);
                    VentanaMaestra v = new VentanaMaestra();
                    v.setVisible(true);
                    v.setLocationRelativeTo(null);
                } catch (Exception ex) {
                    Logger.getLogger(VentanaMaestra.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenuItem jMenuTodosLosPedidos;
    private javax.swing.JMenu jMenuVentanas;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JDesktopPane jdpPanelPrincipal;
    // End of variables declaration//GEN-END:variables
}
